chore(bin): update `loom` script to use `nextest`
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

diff --git a/bin/loom b/bin/loom
--- a/bin/loom
+++ b/bin/loom
@@ -1,11 +1,32 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
+bindir=$( cd "${BASH_SOURCE[0]%/*}" && pwd )
+rootdir=$( cd "$bindir"/.. && pwd )
+
+# shellcheck source=_util.sh
+. "$bindir"/_util.sh
+
+cd "$rootdir"
+
+# assume `cargo nextest` is present
+testcmd=(cargo nextest run --cargo-profile loom --profile loom)
+
+if ! cargo --list | grep -q "nextest"; then
+    err "missing cargo-nextest executable"
+    if confirm "      install it?"; then
+        cargo install cargo-nextest
+    else
+        echo "okay, using cargo test"
+        testcmd=(cargo test --profile loom)
+    fi
+fi
+
+status "Running" "loom tests"
 set -x
 
-RUSTFLAGS="--cfg loom ${RUSTFLAGS}" \
+RUSTFLAGS="--cfg loom ${RUSTFLAGS:-}" \
 LOOM_LOG="${LOOM_LOG:-debug}" \
 LOOM_LOCATION=true \
-cargo test \
-    --profile loom \
-    --lib \
-    "$@"
+    "${testcmd[@]}" --lib "$@"
