chore: factor out changelog updating script
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -11,37 +11,13 @@ FLAGS:
 
 set -euo pipefail
 
-cd "$(dirname "$0")"/..
+bindir=$( cd "${BASH_SOURCE[0]%/*}" && pwd )
+rootdir=$( cd "$bindir"/.. && pwd )
 
-err() {
-    echo -e "\e[31m\e[1merror:\e[0m" "$@" 1>&2;
-}
+# shellcheck source=_util.sh
+. "$bindir"/_util.sh
 
-note() {
-    echo -e "\e[31m\e[1mnote:\e[0m" "$@" 1>&2;
-}
-
-status() {
-    local width=12
-    printf "\e[32m\e[1m%${width}s\e[0m %s\n" "$1" "$2"
-}
-
-confirm() {
-    while read -r -p "$1 [Y/n] " input
-    do
-        case "$input" in
-            [yY][eE][sS]|[yY])
-                return 0
-                ;;
-            [nN][oO]|[nN])
-                return 1
-                ;;
-            *)
-                err "invalid input $input"
-                ;;
-        esac
-    done
-}
+cd "$rootdir"
 
 verify() {
     status "Verifying" "if $crate v$version can be released"
@@ -99,34 +75,6 @@ update_version() {
     fi
 }
 
-update_changelog() {
-    if ! [[ -x "$(command -v git-cliff)" ]]; then
-        err "missing git-cliff executable"
-        if confirm "       install it?"; then
-            cargo install git-cliff
-        else
-            echo "okay, exiting"
-            exit 0
-        fi
-    fi
-
-    status "Updating" "changelog for $crate $version"
-
-    local git_cliff=(
-        git-cliff
-        --include-path "${path}/**"
-        --output "$changelog"
-        --config cliff.toml
-        --tag "$tag"
-    )
-
-    if [[ "$verbose" ]]; then
-        git_cliff+=("$verbose")
-    fi
-
-    "${git_cliff[@]}"
-}
-
 publish() {
     status "Publishing" "$crate v$version"
     cd "$path"
@@ -153,6 +101,18 @@ publish() {
         "${git_tag[@]}"
     fi
 }
+
+update_changelog() {
+    # shellcheck source=update-changelog
+    . "$bindir"/update-changelog
+    changelog_status="$?"
+
+    if ! "$changelog_status"; then
+        err "failed to update changelog"
+        exit "$changelog_status"
+    fi
+}
+
 
 verbose=''
 dry_run=''
@@ -210,16 +170,7 @@ if [[ "${errexit+errexit}" ]]; then
     exit 1
 fi
 
-mycoprefix='mycelium-';
-if [[ -d $crate ]]; then
-    path="$crate"
-elif [[ -d "${crate#"$mycoprefix"}" ]]; then
-    path="${crate#"$mycoprefix"}"
-else
-    err "unknown crate $crate"
-    echo "$usage"
-    exit 1
-fi
+path=$(crate_path "$crate")
 
 cargo_toml="${path}/Cargo.toml"
 changelog="${path}/CHANGELOG.md"
